### ISSUE TITLE
Any key doesn't work in commande

### ISSUE THREAD

**Issue by The33Coder** [zegervdv/homebrew-zathura#10] opened 2015-10-05 23:08 UTC
Hello
I installed zathura with brew on my el capitan but none keys work in commande line.
The j,k,h,l,o and other key work correctly in normal mode. The only key to work in commande line is Esc.
An idea from this isue?

**Comment by zegervdv** [comment] 2015-10-22 18:17
Sorry for my late response, but I indeed see the same issue.
I have no immediate idea as to why it stopped working, but I believe only the developers of zathura will be able to solve this.

**Comment by The33Coder** [comment] 2015-10-24 01:21
Thanks for you response

**Comment by drselump14** [comment] 2015-11-13 20:46
+1 for this issue

**Comment by Boelensman1** [comment] 2015-11-27 09:17
am also having this problem

**Comment by zegervdv** [comment] 2015-12-24 12:58
Good news! The issue seems to be solved in the newest girara version (0.2.5).
I'm working on getting the new zathura version to work as well.

**Comment by jamesalexanderdickerson** [comment] 2016-01-08 08:45
Also having this issue. The navigation keys work, but when I try to follow a link, nothing I type after hitting 'f' will work.

**Comment by itsmealwin** [comment] 2016-01-09 15:02
I can confirm this issue, this renders the search function to be useless under mac os el capitan..

**Comment by zegervdv** [comment] 2016-01-13 18:35
Sadly I have no idea why it's not working on El Cap. I believe this should be raised to the developers.

**Comment by Boelensman1** [comment] 2016-02-09 04:16
I submitted a report of this bug on their bugtracker today, lets hope they will fix it.

https://bugs.pwmt.org/project/zathura/issue/610

**Comment by solvation** [comment] 2016-02-13 09:43
For what its worth: The same behaviour shows under FreeBSD 11. Although the backspace key seems to also be working in addition to the  Esc key. I got ":open" to the command prompt by pressing o, wasn't able to add anything or execute the command with the enter key but could use backspace to erase it. Strange.

**Comment by solvation** [comment] 2016-02-13 10:20
Zathura uses girara for the input handling. Just checked with jumanji browser under FreeBSD 11 which also utilizes girara and it shows the exact same behaviour on the input bar. So maybe we should report the bug at https://bugs.pwmt.org/project/girara/ too?

**Comment by solvation** [comment] 2016-02-25 02:58
Under FreeBSD 11 the problem is related with the Native Language Support Option. If I disable NLS in girara and zathura and recompile the ports instead of using the binary packages everything workes fine.

**Comment by zegervdv** [comment] 2016-03-28 10:18
Thanks for the tip @solvation .
I've been looking at the makefiles, but I don't see anything about NLS. Could you explain how you disabled it?

**Comment by solvation** [comment] 2016-03-28 11:32
@zegervdv 
NLS might be something FreeBSD specific. 
The option is defined in the ports makefile -see here for girara which I actually suspect to be the problem:
http://svnweb.freebsd.org/ports/head/x11-toolkits/girara/Makefile?revision=404308&view=markup

It seems to somehow patch the girara buildfiles in a way that it again works with FreeBSD. Looking at the bottom of the makefile under "post-patch-NLS-off" it seems to remove all additions of the PO stuff from the makefile. I'm not sure though if it does more somewhere else since I'm no expert with FreeBSD port files.

You can read about PO on FreeBSD here:
https://www.freebsd.org/doc/en_US.ISO8859-1/books/fdp-primer/po-translations.html 

I was just glad that disabling NLS cured the symptoms and I didn't investigate much further from that point on. Hope you'll find a similar solution to get it working in homebrew again.

**Comment by zegervdv** [comment] 2017-01-14 10:42
241dcd5 seems to solve the issue, can you confirm?

**Comment by drselump14** [comment] 2017-01-14 10:49
It works in my computer... thanks ... :)

**Comment by zegervdv** [comment] 2017-01-24 18:22
Ok, I guess we can close this one.
If the issue is still not resolved with this version you can reopen it.

**Closed by zegervdv** 2017-01-24 18:22 UTC
