### ISSUE TITLE
HiDPI/retina support

### ISSUE THREAD

**Issue by ubuntu0** [zegervdv/homebrew-zathura#9] opened 2015-09-01 16:18 UTC
I got the HiDPI support from the developer's issue tracker as following:
https://bugs.pwmt.org/issue461

Is it possible to add HiDPI support in brew as mentioned in the comment.

**Comment by zegervdv** [comment] 2015-09-01 18:17
I have only looked at it briefly, but this it seems that the library in the issue is not (yet) used in zathura.

For now it seems we must wait until they release this.

**Comment by jottr** [comment] 2016-06-07 16:18
Any update on this?

**Comment by TerryGeng** [comment] 2017-06-27 11:32
It has been nearly two years but this is still unchanged.

**Comment by phye** [comment] 2017-07-25 04:29
Any updates on this? 
Seems that the issue link above points to nothing.

**Comment by zegervdv** [comment] 2017-08-12 09:50
It seems the bug has moved [here](https://bugs.pwmt.org/project/zathura/issue/429).

Can any of you try experimenting with the `GDK_SCALE=2` when starting zathura and see if that helps?

**Comment by yaodis** [comment] 2018-02-22 16:18
@zegervdv I tried `GDK_SCALE`, it's not work. Actually there is an update in [this](  https://git.pwmt.org/knuesel/zathura/tree/feature/hidpi) tree fixed this problem. Already tried out on my computer. you can update formula point to this

**Comment by Alok** [comment] 2018-04-27 06:46
@yaodis That's great, retina support would be nice.

**Comment by zegervdv** [comment] 2018-05-01 15:59
I updated to zathura version `0.3.9`, can you check out if the HDPI works?

**Comment by zegervdv** [comment] 2018-08-14 08:11
Anyone had any luck trying the latest version with HDPI screens?

**Comment by phye** [comment] 2018-08-15 04:46
By latest version are you referring to 0.3.9?
I've been using 0.3.9 zathura on a 4K monitor for months and surely you can feel the difference between 0.3.9 and any other previous versions. 

![wechatworkscreenshot_5044cf8a-4527-4017-b796-5db56e6b09d3](https://user-images.githubusercontent.com/3255399/44132016-241e8ee8-a089-11e8-8dee-2849b612a549.png)

**Comment by zegervdv** [comment] 2018-08-18 09:06
Thanks for letting me know.
I'll close this issue then, if there are still problems you can open a new one.

**Closed by zegervdv** 2018-08-18 09:06 UTC
