### ISSUE TITLE
~$ brew install zathura-pdf-mupdf fails on macOS 10.14.6

### ISSUE THREAD

**Issue by marekkowalczyk** [zegervdv/homebrew-zathura#44] opened 2020-02-22 14:58 UTC
`==> Installing zathura-pdf-mupdf from zegervdv/zathura
==> Downloading https://github.com/pwmt/zathura-pdf-mupdf/archive/0.3.4.tar.gz
==> Downloading from https://codeload.github.com/pwmt/zathura-pdf-mupdf/tar.gz/0.3.4
######################################################################## 100.0%
==> mkdir build
==> meson build --prefix /usr/local/Cellar/zathura-pdf-mupdf/0.3.4
==> cd build && ninja && ninja install
Last 15 lines from /Users/marekkowalczyk/Library/Logs/Homebrew/zathura-pdf-mupdf/03.cd:
[6/11] Compiling C object 'pdf-mupdf@sha/zathura-pdf-mupdf_document.c.o'.
[7/11] Compiling C object 'pdf-mupdf@sha/zathura-pdf-mupdf_utils.c.o'.
[8/11] Compiling C object 'pdf-mupdf@sha/zathura-pdf-mupdf_select.c.o'.
[9/11] Compiling C object 'pdf-mupdf@sha/zathura-pdf-mupdf_render.c.o'.
[10/11] Compiling C object 'pdf-mupdf@sha/zathura-pdf-mupdf_search.c.o'.
FAILED: pdf-mupdf@sha/zathura-pdf-mupdf_search.c.o 
clang -Ipdf-mupdf@sha -I. -I.. -I/usr/local/Cellar/libffi/3.2.1/lib/libffi-3.2.1/include -I/usr/local/Cellar/pcre/8.44/include -I/usr/local/Cellar/glib/2.62.5/include/gio-unix-2.0 -I/usr/local/Cellar/glib/2.62.5/include -I/usr/local/Cellar/glib/2.62.5/include/glib-2.0 -I/usr/local/Cellar/glib/2.62.5/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/atk/2.34.1/include/atk-1.0 -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/gdk-pixbuf/2.40.0/include/gdk-pixbuf-2.0 -I/usr/local/Cellar/libepoxy/1.5.4/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/Cellar/pixman/0.38.4/include/pixman-1 -I/usr/local/Cellar/cairo/1.16.0_2/include/cairo -I/usr/local/Cellar/fribidi/1.0.8/include/fribidi -I/usr/local/Cellar/graphite2/1.3.13/include -I/usr/local/Cellar/harfbuzz/2.6.4/include/harfbuzz -I/usr/local/Cellar/pango/1.44.7/include/pango-1.0 -I/usr/local/Cellar/gtk+3/3.24.14/include/gtk-3.0 -I/usr/local/Cellar/girara/0.3.3/include -I/usr/local/Cellar/zathura/0.4.4/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -std=c11 -g -DVERSION_MAJOR=0 -DVERSION_MINOR=3 -DVERSION_REV=4 -D_DEFAULT_SOURCE -Wall -Wextra -pedantic -Werror=implicit-function-declaration -Werror=vla -fvisibility=hidden -MD -MQ 'pdf-mupdf@sha/zathura-pdf-mupdf_search.c.o' -MF 'pdf-mupdf@sha/zathura-pdf-mupdf_search.c.o.d' -o 'pdf-mupdf@sha/zathura-pdf-mupdf_search.c.o' -c ../zathura-pdf-mupdf/search.c
../zathura-pdf-mupdf/search.c:42:23: error: expected expression
  fz_quad* hit_bbox = fz_malloc_array(mupdf_page->ctx, N_SEARCH_RESULTS, sizeof(fz_quad));
                      ^
/usr/local/include/mupdf/fitz/context.h:296:9: note: expanded from macro 'fz_malloc_array'
        ((TYPE*)Memento_label(fz_malloc(CTX, (COUNT) * sizeof(TYPE)), #TYPE "[]"))
               ^
1 error generated.
ninja: build stopped: subcommand failed.
`

**Comment by zegervdv** [comment] 2020-02-22 16:25
There is an update for `zathura-pdf-mupdf` which seems to resolve this.
I've updated the package to `v0.3.5`.

**Comment by MarkusLohmayer** [comment] 2020-02-29 13:05
Sorry if this is not related but I think it might be:
I did a brew install zathura-pdf-mupdf
and when I launched a file then I get
```
error: Unknown file type: 'dyn.agq80g2psr311kkdtsbw06kdaf741g3pwsq1042pwrr41gp5wqz30n2pwqryc8qvugk2ca5dtrb00c8pfskuc4kdftbw1e353ebuwa5dmr3x1n2maq33gc5xdqeugq55web2g86xyfzygc5pmrv4g85xmqf1ca653sr4gn5pxf7u1e7dmqr0gnppftbw1e353fz0gw5xhszuw43xwqf1gg2mtsvw1up5yqz6c82pwsvy0g5dffzw1u3pwq76w45dmr3x1n2mrq33gc5xdqe1ha3dge6ucu5xteb31n25kebxgw5dfeb11ekderf3gn25yr73hwnk'
```

**Comment by zegervdv** [comment] 2020-03-01 18:47
Strange, I can't reproduce it. Did you try with different pdfs, just to rule out there is not something special about this one?

Are you using the latest versions?

**Comment by MarkusLohmayer** [comment] 2020-03-02 07:45
@zegervdv Yes I did a `brew update` before I did `brew install zathura-pdf-mupdf` at the time.
I am really sorry to say that I might have been mistaken.
Because I myself tried to reproduce it and now it works (also with the same PDF I tried before).
From my perspective, this issue can be closed, thanks! ^^

**Comment by zegervdv** [comment] 2020-03-02 08:30
No worries :)
Seeing it works for at least someone else I'm going to close this.
@marekkowalczyk feel free to re-open if you still have issues.

**Closed by zegervdv** 2020-03-02 08:30 UTC
