### ISSUE TITLE
Dependency "girara-gtk3" not found, tried pkgconfig and cmake

### ISSUE THREAD

**Issue by anishmittal2020** [zegervdv/homebrew-zathura#35] opened 2019-04-17 10:05 UTC
```bash
$ brew info zathura
zegervdv/zathura/zathura: stable 0.4.3
https://pwmt.org/projects/zathura/
Not installed
From: https://github.com/zegervdv/homebrew-zathura/blob/master/zathura.rb
==> Dependencies
Required: pkg-config ✔, libmagic ✔, gettext ✔, girara ✔, gnome-icon-theme ✔, glib ✔, desktop-file-utils ✔, intltool ✔, sphinx-doc ✔, meson --head ✔
Optional: synctex ✘
==> Requirements
Required: x11 ✔
==> Options
--with-synctex
        Build with synctex support
```

## Brew info shows that all dependencies are met. But, while installing it is not finding one (girara-gtk3)

```bash
$ brew install zathura
Updating Homebrew...
==> Installing zathura from zegervdv/zathura
==> Downloading https://github.com/pwmt/zathura/archive/0.4.3.tar.gz
Already downloaded: /home/nikhil/.cache/Homebrew/downloads/805e8ef758797bf5f1aa56d6133c776105bcaf9d306c54b8321d668217a178e8--zathura-0.4.3.tar.gz
==> mkdir build
==> meson build --prefix /home/linuxbrew/.linuxbrew/Cellar/zathura/0.4.3
Last 15 lines from /home/nikhil/.cache/Homebrew/Logs/zathura/02.0.4.3:
Build dir: /tmp/zathura-20190417-15553-iaixga/zathura-0.4.3/build
Build type: native build
Project name: zathura
Project version: 0.4.3
Native C compiler: gcc-5 (gcc 5.5.0 "gcc-5 (Homebrew gcc 5.5.0_4) 5.5.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library m found: YES
Found pkg-config: /home/linuxbrew/.linuxbrew/opt/pkg-config/bin/pkg-config (0.29.2)
Found CMake: /usr/bin/cmake (3.10.2)
Dependency girara-gtk3 found: NO (tried pkgconfig and cmake)

meson.build:40:0: ERROR: Dependency "girara-gtk3" not found, tried pkgconfig and cmake
```

**Comment by zegervdv** [comment] 2019-04-17 10:45
Is your girara version up to date? Could you try a brew update girara?

**Comment by anishmittal2020** [comment] 2019-04-17 14:47
```
$ brew upgrade girara
Error: zegervdv/zathura/girara 0.3.2 already installed
```

Do you think if I have to define environmewnt variable for `pkgconfig`. I am using Ubuntu 18.04

**Comment by zegervdv** [comment] 2019-04-17 14:48
Oh, this is a macOS version of zathura :) 
I'm not expecting it to work on Linux.

**Comment by anishmittal2020** [comment] 2019-04-17 16:06
Many macOs software work via linux brew. I am actually using quite a lot of them. Everything is working fine, just that it is not able to identify the path of the dependency.

**Comment by zegervdv** [comment] 2019-04-17 17:11
Okay cool, I had no idea they were so interchangeable. 
I’ll have to setup a VM to reproduce this myself.

**Comment by anishmittal2020** [comment] 2019-04-17 20:41
I have installed the following with brew:

- pandoc
- pandoc-citeproc librsvg
- mps-yt
- mpv
- youtube-dl
- hub
- [zaquestion/lab: Lab wraps Git or Hub, making it simple to clone, fork, and interact with repositories on GitLab](https://github.com/zaquestion/lab)
- shfmt
- shellcheck
- neovim

**Comment by zegervdv** [comment] 2019-04-17 20:54
What happens if you “brew link girara” before installing zathura?

**Comment by anishmittal2020** [comment] 2019-04-17 20:55
```bash
$ brew link girara
Warning: Already linked: /home/linuxbrew/.linuxbrew/Cellar/girara/0.3.2
To relink: brew unlink girara && brew link girara
```

**Comment by anishmittal2020** [comment] 2019-04-17 20:58
From man pkg-config:

```bash
       pkg-config  retrieves information about packages from special metadata files. These files
       are named after the package, and has a .pc extension.  On most systems, pkg-config  looks
       in     /usr/lib/pkgconfig,     /usr/share/pkgconfig,     /usr/local/lib/pkgconfig     and
       /usr/local/share/pkgconfig for these files.  It will additionally look in the colon-sepa‐
       rated  (on  Windows,  semicolon-separated)  list of directories specified by the PKG_CON‐
       FIG_PATH environment variable.
```

**Comment by anishmittal2020** [comment] 2019-04-17 21:10
So I added the environmental variable `PKG_CONFIG_PATH`. The following is all the path recognized by pkg-config. [Source](https://askubuntu.com/questions/210210/pkg-config-path-environment-variable)

```
$ echo $(pkg-config --variable pc_path pkg-config)${PKG_CONFIG_PATH:+:}${PKG_CONFIG_PATH}

/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:/home/linuxbrew/.linuxbrew/Cellar/girara/0.3.2/lib/x86_64-linux-gnu/pkgconfig
```

**Comment by anishmittal2020** [comment] 2019-04-17 21:28
I found this suggestion: `meson configure -Dlibdir=lib` at [girara libraries should be installed in /usr/local/lib ? - Issue #34 - girara](https://bugs.pwmt.org/project/girara/issue/34). Do you know what commands I have to type to specify this? I thought of trying it.

**Comment by zegervdv** [comment] 2019-04-18 18:30
Normally homebrew should set up all the variables it needs based on the dependencies, because if they are installed with brew it knows where they are.
I'm setting up an ubuntu docker image to do some local testing, hang tight.

**Comment by zegervdv** [comment] 2019-04-18 18:36
What you could try is do a `brew edit zathura` and above line 29 add:
```ruby
system "meson configure -Dlibdir=lib"
```

**Comment by anishmittal2020** [comment] 2019-04-19 01:36
```bash
$ brew --prefix
/home/linuxbrew/.linuxbrew
```

```bash
$ brew link girara
Warning: Already linked: /home/linuxbrew/.linuxbrew/Cellar/girara/0.3.2

$ ls /home/linuxbrew/.linuxbrew/Cellar/girara/0.3.2/lib/x86_64-linux-gnu
pkgconfig/  libgirara-gtk3.so@  libgirara-gtk3.so.3@  libgirara-gtk3.so.3.1*
```
As per [Meson Website](https://mesonbuild.com/Builtin-options.html#directories): libdir  option is the subdirectory of prefix. And default libdir is `/usr/local`.

In your receipe, prefix is $(brew --prefix)  [Line Number 29 ](https://github.com/zegervdv/homebrew-zathura/blob/master/zathura.rb). So we have to change this line 29 (as you said).

So to override the default libdir I inserted `--libdir=.`

```
system "meson build --prefix #{prefix} --libdir=."
```

But unfortunately this doesn't works

**Comment by zegervdv** [comment] 2019-04-19 15:54
You need to point it to the girara prefix. The `prefix` defined here is the one for zathura.
You could try hardcoding it for now, I'll have to look up how to get the prefix of other packages in homebrew.

**Comment by zegervdv** [comment] 2019-04-27 08:48
Took a while to set up a test case but I was able to reproduce on Ubuntu 18.04.
I've just pushed a patch which allowed me to build zathura successfully.

**Comment by zegervdv** [comment] 2019-04-27 09:02
but it's not finding the `girara-gtk3` libs now, there must be something off with the install...

**Comment by zegervdv** [comment] 2019-04-27 09:13
So it seems homebrew isn't linking the girara `lib` directory to search path.
```
LD_LIBRARY_PATH=$(brew --prefix girara)/lib/x86_64-linux-gnu zathura
```
works for now, but that is not a clean solution.

**Comment by anishmittal2020** [comment] 2019-04-27 23:10
zathura is installed without error. But I get the following:

```bash
$ zathura -v

error: could not open plugin directory: /home/linuxbrew/.linuxbrew/Cellar/zathura/0.4.3/Cellar/zathura
/home/linuxbrew/.linuxbrew/bin/zathura: symbol lookup error: /home/linuxbrew/.linuxbrew/bin/zathura: undefined symbol: girara_version
```

**Comment by zegervdv** [comment] 2019-04-29 06:03
Did you use the LD_LIBRARY_PATH variable? 
And if you just run zathura does it show the GUI?

**Comment by anishmittal2020** [comment] 2019-04-29 07:20
Yes my bashrc has `LD_LIBRARY_PATH=$(brew --prefix girara)/lib/x86_64-linux-gnu
`.

Yes it shows as follows:

![image](https://user-images.githubusercontent.com/42092626/56881228-0bddca00-6a60-11e9-9225-ccd79b388458.png)

**Comment by zegervdv** [comment] 2019-04-29 07:49
Okay. That error is because you have no plugins installed, can you try the zathura-ps ? And follow the instructions in the caveat to create the plugin directory

**Comment by anishmittal2020** [comment] 2019-04-29 17:33
I will update after pdf works as being tracked in [zathura-pdf-poppler: Utils::InreplaceError: inreplace failed · Issue #36 · zegervdv/homebrew-zathura](https://github.com/zegervdv/homebrew-zathura/issues/36)

Thanks!

**Comment by pasekaalex** [comment] 2019-05-08 17:07
having same exact issue. on OSX mojave 10.14.4

**Comment by zegervdv** [comment] 2019-05-09 10:59
And does the workaround work for you?

**Comment by JackRab** [comment] 2019-05-17 01:06
some issue here on OSX mojave 10.14.4

==> mkdir build
==> meson build --prefix /usr/local/Cellar/girara/0.3.2
Last 15 lines from /Users/jack/Library/Logs/Homebrew/girara/02.0.3.2:
2019-05-16 21:04:27 -0400

meson build --prefix /usr/local/Cellar/girara/0.3.2

Traceback (most recent call last):
  File "/usr/local/Cellar/meson/0.50.1/libexec/bin/meson", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/zegervdv/homebrew-zathura/issues

These open issues may also help:
Dependency "girara-gtk3" not found, tried pkgconfig and cmake https://github.com/zegervdv/homebrew-zathura/issues/35

**Comment by JackRab** [comment] 2019-05-17 15:52
Following this [link](https://github.com/asciinema/asciinema/issues/260) solves my problem.

**Comment by AgentDS** [comment] 2019-05-28 19:09
> Following this [link](https://github.com/asciinema/asciinema/issues/260) solves my problem.

it works but I got 1 more python in my system now... (+_+)

**Comment by chu-** [comment] 2020-02-15 02:18
python version issue.
brew unlink python #unlink python 2
brew install python #install the latest python 3
brew install zathura
done.

**Comment by zegervdv** [comment] 2020-02-15 11:10
This is an issue in linuxbrew (for Linux) not homebrew (for Mac OS X).
I'm closing this one as seems to confuse people.

**Closed by zegervdv** 2020-02-15 11:10 UTC

**Comment by waldyrious** [comment] 2020-03-27 19:19
This seems similar to an issue I had [here](https://github.com/phase1geo/Outliner/issues/5) (it may be relevant for #42 as well). Quoting a [comment](https://github.com/phase1geo/Outliner/issues/5#issuecomment-604070838) there:

> Homebrew's `pkg-config` only reports packages installed by Homebrew

For me the solution was to use the distro's `pkg-config` instead of Homebrew's.
